#!/bin/bash
# Enable database sharding, run this script after 'mkshard'
# Make sharded collection(s) by _id:hashed key
# $1 - database name to shard (create sharded)
# $2 ... - collection(s) to shard in the database (create sharded by _id: hashed)

DB=$1  ; shift
COL=$1 ; shift

mongo --norc --eval "load(\"$HOME/.mongorc.js\"); sh.enableSharding(\"$DB\")"
while [ "$COL" != "" ]; do
  mongo --norc --eval "load(\"$HOME/.mongorc.js\"); sh.shardCollection(\"$DB.$COL\", { \"_id\":\"hashed\" }, false)"
  COL=$1 ; shift
done
